"""add auctions and items

Revision ID: 8190260dea41
Revises: c4873d6df525
Create Date: 2026-10-04 12:49:28.619644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8190260dea41'
down_revision: Union[str, None] = 'c4873d6df525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('catalog_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('tax_label', sa.String(length=16), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('buyer_premium_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('per_item_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cc_processing_pct', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'catalog_id', name='uq_auctions_source_catalog')
    )
    op.create_index(op.f('ix_auctions_source_id'), 'auctions', ['source_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auction_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('raw_title', sa.String(length=1000), nullable=False),
    sa.Column('current_bid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_id', 'item_id', name='uq_items_auction_item')
    )
    op.create_index(op.f('ix_items_auction_id'), 'items', ['auction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_auction_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_auctions_source_id'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
